name: unity4_academy
description: UNITY4 ACADEMY - Modern, çok platformlu eğitim uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  intl: 0.20.2
  google_fonts: ^6.1.0
  file_picker: ^10.3.8
  url_launcher: ^6.2.6
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  firebase_messaging: ^16.1.0
  firebase_app_check: ^0.4.1+3
  flutter_local_notifications: ^19.5.0
  record: ^6.1.2
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  youtube_player_iframe: ^5.2.2
  http: ^1.6.0
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
dev_dependencies:
  intl_utils: ^2.8.13
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  android_gravity: center
  ios_content_mode: center
  web: false
  android_12:
    image: "assets/images/logo.png"
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
